version: '3'

services:
#  nginx-proxy:
#    image: jwilder/nginx-proxy
#    restart: always
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - /var/run/docker.sock:/tmp/docker.sock:ro
#      - certs:/etc/nginx/certs:ro
#      - vhostd/default.conf:/etc/nginx/vhost.d/default.conf
#      - html:/usr/share/nginx/html
#    labels:
#      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
#
#  letsencrypt:
#    image: jrcs/letsencrypt-nginx-proxy-companion
#    restart: always
#    environment:
#      - NGINX_PROXY_CONTAINER=nginx-proxy
#    volumes:
#      - certs:/etc/nginx/certs:rw
#      - vhostd:/etc/nginx/vhost.d
#      - html:/usr/share/nginx/html
#      - /var/run/docker.sock:/var/run/docker.sock:ro
#      - acme:/etc/acme.sh

  www:
    image: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - vhostd/default_test.conf:/etc/nginx/conf.d/default.conf
      - html:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=sixedges.solutions
      - LETSENCRYPT_HOST=sixedges.solutions
      - LETSENCRYPT_EMAIL=miguelgarciaponce85@gmail.com
#    depends_on:
#      - nginx-proxy
#      - letsencrypt
volumes:
  certs:
  html:
  vhostd:
  acme: