version: '3'
services:
  db:
    image: mysql:8.0.19
    container_name: db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  wordpress:
    image: wordpress:5.4.1-php7.4-apache
    container_name: wordpress
    depends_on:
      - db
    restart: always
    expose:
      - "8004"
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=root
      - WORDPRESS_DB_NAME=wordpress
      - VIRTUAL_HOST=mafenoboa.com
      #- VIRTUAL_PORT=8004
      - LETSENCRYPT_HOST=mafenoboa.com
      - LETSENCRYPT_EMAIL=miguelgarciaponce85@gmail.com
    volumes:
      - ./wordpress:/var/www/html

volumes:
  data:
  wordpress:

networks:
  default:
    external:
      name: nginx-proxy